---
- name: reset zookeeper data
  file:
    path: "{{ zookeeper_version_data_dir }}"
    state: absent

- name: restart zookeeper
  service:
    name: "{{zookeeper_service_name}}"
    state: "restarted"
    sleep: 5
